modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/unascribed/BlockRenderer/issues"
[[mods]]
modId="blockrenderer"
version="${file.jarVersion}"
displayName="BlockRenderer"
displayURL="https://unascribed.com"
logoFile="logo-blockrenderer.png"
credits="Una, xbony2, modmuss50, AterAnimAvis, Brian Paul (TR Library)"
authors="Una"
description="It renders blocks and items."

[[dependencies.block_renderer]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.block_renderer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
