modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/AterAnimAvis/BlockRenderer/issues"
[[mods]]
modId="block_renderer"
version="${file.jarVersion}"
displayName="BlockRenderer"
displayURL="https://unascribed.com"
logoFile="logo-blockrenderer.png"
credits="Una, xbony2, modmuss50, AterAnimAvis, Brian Paul (TR Library)"
authors="Una"
description="It renders blocks and items."

[[dependencies.block_renderer]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.block_renderer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
